#diary api routing
diary_index:
  url: /diary/list.json
  param: { module: diary, action: list, sf_format: json }
  requirements: { sf_method: [get] }

diary_post:
  url: /diary/post.json
  param: { module: diary, action: post, sf_format: json }
  requirements: { sf_method: [post, get] }

diary_delete:
  url: /diary/delete.json
  param: { module: diary, action: delete, sf_format: json }
  requirements: { sf_method: [get] }

diary_show:
  url: /diary/show.json
  param: { module: diary, action: show, sf_format: json }
  requirements: { sf_method: [get] }

diary_comment_post:
  url: /diary_comment/post.json
  param: { module: diaryComment, action: post, sf_format: json }
  requirements: { sf_method: post }
