smtDiaryMember:
  caption:
    ja_JP: "自分の日記(最新4件表示)"
    en_US: "Show latest 4 diary entries of mine"
  description:
    ja_JP: "自分の日記エントリのうち､最新の4件を表示します｡"
    en_US: "Show latest 4 diary entries of mine"
  component: [diary, smtDiaryMember]

smtDiaryList:
  caption:
    ja_JP: "SNSメンバーの日記(最新4件表示)"
    en_US: "Show latest 4 diary entries of sns member"
  description:
    ja_JP: "SNSメンバーの日記エントリのうち､最新の4件を表示します｡"
    en_US: "Show latest 4 diary entries of sns member"
  component: [diary, smtDiaryList]

smtDiaryListFriend:
  caption:
    ja_JP: "フレンドの日記(最新4件表示)"
    en_US: "Show latest 4 diary entries of friend"
  description:
    ja_JP: "フレンドの日記エントリのうち､最新の4件を表示します｡"
    en_US: "Show latest 4 diary entries of friend"
  component: [diary, smtDiaryListFriend]
